### ISSUE TITLE
Should support over 4.2 Giga adding files

### ISSUE THREAD

**Issue by ramihoo** [jaime-olivares/zipstorer#17]
Old version Zipstorer did not support big files if added file size was over uint range :). I have not tested this new version but I had feeling, when I looked source code, that there is same problem. You should check this out.

**Comment by jaime-olivares** [comment]
I will evaluate this feature. I don't have any explicit management of 4GB+ files.

**Comment by stribizhev** [comment]
I confirm that Version: 3.4.0 (August 4, 2017) contains the same "bug": trying to extract a 6GB+ file results in file truncation (at about 4GB). It would be really nice to fix this limitation.

**Comment by DarkByte7** [comment]
Try switching the type from a `uint` to `long`. It should allow a greater size in bytes.

**Comment by jaime-olivares** [comment]
Let me know if that works for doing the change

**Comment by jaime-olivares** [comment]
I have reviewed the documentation for ZIP64. This is not a trivial task. Many things to consider. 
See: https://www.loc.gov/preservation/digital/formats/digformatspecs/APPNOTE%2820120901%29_Version_6.3.3.txt

**Comment by usr-sse2** [comment]
@ramihoo @stribizhev, Check out my ZipStorer64 fork: https://github.com/usr-sse2/zipstorer

**Comment by jaime-olivares** [comment]
@usr-sse2 you can always create pull request so we consolidate more features in a single project.

**Comment by jaime-olivares** [comment]
Added support for Zip64 in version 3.6.0

Please let me know if there is any issue
