### ISSUE TITLE
Proper Date/Time 

### ISSUE THREAD

**Issue by mgholam** [jaime-olivares/zipstorer#23]
Can you add the proper date/time in the extended header instead of the brain dead dos format date/time?

**Comment by jaime-olivares** [comment]
Please elaborate more. Does the standard date/time is not working?

**Comment by mgholam** [comment]
The standard date/time is working but giving only even seconds and I need exact the time. 
As a workaround I'm using the zip comment to store the file exact date time.
See my article : https://www.codeproject.com/Articles/1224849/TorpedoSync

**Comment by jaime-olivares** [comment]
I have added NTFS FileTime extra section. That can store dates with a resolution of 100 ns
