### ISSUE TITLE
Thanks for giving CIA what they want...

### ISSUE THREAD

**Issue by invictus-c** [jaime-olivares/zipstorer#25]
Version: 2.35 (March 14, 2010)

**Comment by jaime-olivares** [comment]
Sorry, not following you. What that means?

**Comment by JebSmith** [comment]
Oh shit, you did give the CIA what they wanted... Look in the source of scribbles: https://github.com/zakybstrd21215/Wikileaks-Scribbles-CIA/tree/master/Scribbles_src/Scribbles 

they used your library...

**Comment by jaime-olivares** [comment]
Well, I am glad to know people is using my library, no matters who they are...
