### ISSUE TITLE
DosTimeToDateTime

### ISSUE THREAD

**Issue by abou-hafs** [jaime-olivares/zipstorer#26]
I'm not good programmer, so I can't describe the issue will .. this exception showing with some files, not with all, and fire from DosTimeToDateTime Function
System.ArgumentOutOfRangeException: 'Hour, Minute, and Second parameters describe an un-representable DateTime.'

**Comment by jaime-olivares** [comment]
Hi, thanks for the report. It is enough for controlling it. Will be incorporated in the next release.

**Comment by jaime-olivares** [comment]
Solved. To be released soon.
