### ISSUE TITLE
DateTimeToDosTime exception

### ISSUE THREAD

**Issue by benchen71** [jaime-olivares/zipstorer#27]
I'm using zipstorer.vb in an application to open and save EPUB files.  I've discovered that the saving process is crashing in the DateTimeToDosTime function when files in the EPUB have "weird" dates.  (Note that they open fine.)

The error that is given is "Arithmetic operation resulted in an overflow".  If I check the value of the variable _dt, I get the following values:
_dt = #12/31/2107 11:00:00 PM#
_dt.Second = 0
_dt.Minute = 0
_dt.Hour = 23
_dt.Day = 31
_dt.Month = 12
_dt.Year = 2107

When I look at the EPUB file in 7-zip, the file that zipstorer is currently trying to save to the stream has a date modified 1980-01-01 07:00 (even though the created date is 2011-06-02 05:35).

Any idea what's causing the overflow?

**Comment by benchen71** [comment]
Actually, now that I look more closely, the date modified for the problem file is originally 1980-01-01 07:00 (in the original EPUB).  But the date modified of the unpacked file, the one that zipstorer is later crashing on when it tries to save it, is 31/12/2107 11:00 PM.

So now I see that the problem might be being caused by the _open_ process, which would mean DosTimeToDateTime is not handling the original date modified.

**Comment by benchen71** [comment]
For an example, see the "mimetype" file in the following:

[Lewis - 4. The Silver Chair.zip](https://github.com/jaime-olivares/zipstorer/files/2108556/Lewis.-.4.The.Silver.Chair.zip)

**Comment by jaime-olivares** [comment]
Hi, I see 2107 in all messages, rather than 2017.
is this a typo?

**Comment by benchen71** [comment]
No it's not a typo.  As far as I can tell, the open process takes the original file date 1980-01-01 07:00 and gives the unpacked file a date of 31/12/2107 11:00 PM.  Then when my program later tries to save the zip file, zipstorer crashes.

**Comment by benchen71** [comment]
I have implemented a work-around.  The function DosTimeToDateTime in the zipstorer.vb now looks like this:

```
    Private Function DosTimeToDateTime(ByVal _dt As UInteger) As DateTime
        Dim year As Integer = CType(_dt >> 25, Integer) + 1980
        Dim month As Integer = CType(_dt >> 21, Integer) And 15
        Dim day As Integer = CType(_dt >> 16, Integer) And 31
        Dim hours As Integer = CType(_dt >> 11, Integer) And 31
        Dim minutes As Integer = CType(_dt >> 5, Integer) And 63
        Dim seconds As Integer = CType(_dt And 31, Integer) * 2

        If ((year >= 2107) Or (month = 0) Or (day = 0)) Then Return DateTime.Now

        Return New DateTime(year, month, day, hours, minutes, seconds)
    End Function
```

It's a bit of a fudge, but at least it prevents the exception error!

**Comment by jaime-olivares** [comment]
Solved by reading the NTFS FileTime extra info.

**Comment by benchen71** [comment]
Thanks for this.

I've incorporated your changes into my program, converting them into vb.net in the process, and will do some testing.  But initial tests look good!
