### ISSUE TITLE
Extract to folder

### ISSUE THREAD

**Issue by Delaley** [jaime-olivares/zipstorer#3]
How do I extract to a folder not a file.

**Comment by Delaley** [comment]
Okay I mananage to Extract to a directory however all text seems to be wrongly encoded. Any solution

**Comment by Delaley** [comment]
Okay I manage to Extract to a directory however all text seems to be wrongly encoded. Any solution

**Comment by jaime-olivares** [comment]
Delaley, the library doesn't do anything with the content, either text or binary. If you have an encoding problem, it may be related to the receiving text stream object/class.
