### ISSUE TITLE
Large corrupt zip archive takes indefinitely long time to open

### ISSUE THREAD

**Issue by sepiel** [jaime-olivares/zipstorer#37]
Hello,
I'm using ZipStorer with sometimes large zip archives. It could happen that a download of a large zip archive (above 1GB) is interrupted and a corrupt zip archive without central direcotry structure is caused. When opening such a file it takes an indefinitely long time (definitely longer than 10 minutes for 2GB) for the ZipStorer to search the whole zip for a "End of central directory record" (cause it did not exist).

Is there the possibility to get an earlier feedback that the zip archive is corrupted. A possible solution could be to only search in the last MB of the zip for this record? The only variable size in this record is a "comment" value.

It would be valuable to get a quicker feedback of a broken zip.

**Comment by jaime-olivares** [comment]
Hi, I will need a concrete example, because it may depend on the content.
