### ISSUE TITLE
Not possible to delete

### ISSUE THREAD

**Issue by michalss** [jaime-olivares/zipstorer#38]
Hi,

First i have to say nice work. I have a problem when i extract all files i would like to remove zip file afterwords, but it wont let me and zip is being lock by this class. Im using zip.dispose and also zip.close, but still it is locked. Any help pls ?

**Comment by jaime-olivares** [comment]
Can you debug if the Dispose occurs? and it occurs before you try to delete?

**Comment by jaime-olivares** [comment]
Duplicated as #41 

Please read my comment there
