### ISSUE TITLE
Async-Support

### ISSUE THREAD

**Issue by Gitii** [jaime-olivares/zipstorer#4]
Hi,

I added some basic support for async-operation.
Its in my fork. Feel free to pull it in here.
I'll test it a bit during development.

Greetings

**Comment by jaime-olivares** [comment]
Hi there, it is an interesting proposal. However, I think it should be provided as a different VS project, as I know there are other people using it in old .net, mono, compact framework, etc. Maybe it would be better to create an additional folder structure here in github.

**Comment by Gitii** [comment]
I updated my fork to the latest version and dropped a few things (and fixed others):
Please see my pull request: https://github.com/jaime-olivares/zipstorer/pull/13
