### ISSUE TITLE
CA1028: Enum storage should be Int32

### ISSUE THREAD

**Issue by mind-bending-forks** [jaime-olivares/zipstorer#40]
The FxCop static analysers are reporting [CA1028](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1028) against [the following line in ZipStorer.cs](https://github.com/jaime-olivares/zipstorer/blob/8fb36065d8992c6beb32b21830e19c998b95826d/src/ZipStorer.cs#L22):

```csharp
public enum Compression : ushort
```

These state that

> Even though you can change this underlying type (from System.Int32), it is not necessary or recommended for most scenarios. No significant performance gain is achieved by using a data type that is smaller than Int32. If you cannot use the default data type, you should use one of the Common Language System (CLS)-compliant integral types, Byte, Int16, Int32, or Int64 to make sure that all values of the enumeration can be represented in CLS-compliant programming languages.

So, please consider making one of the following changes:

* If the fact that it is a `ushort` specifically is relied upon and required, then change its underlying type to `System.UInt16`, otherwise
* alter the code such that its underlying type is the default `System.Int32`.

Thanks.

**Comment by tw-JordanChen** [comment]
>> If you cannot use the default data type, you should use one of the Common Language System (CLS)-compliant integral types, Byte, Int16, Int32, or Int64 to make sure that all values of the enumeration can be represented in CLS-compliant programming languages.
> 
> So, please consider making one of the following changes:
> 
> * If the fact that it is a `ushort` specifically is relied upon and required, then change its underlying type to `System.UInt16`, otherwise
> * alter the code such that its underlying type is the default `System.Int32`.

According to the [wiki](https://en.wikipedia.org/wiki/ZIP_(file_format)#File_headers), the compression method field in the header is 2 byte. If the author takes into account compatibility, this warning could be suppressed without any risk. 
Besides, `ushort` is just a syntactic sugar and it equals to `UInt16`, which is not a CLS-compliant integral type either.

**Comment by jaime-olivares** [comment]
A stated above, this field is not 32 bits but 16 bits.
ushort or UInt is the right type to use for that field, according to the standard.
You may disable that FXCop warning with a directive.
