### ISSUE TITLE
Error encoding 437 .net core 3.1

### ISSUE THREAD

**Issue by gfazzola** [jaime-olivares/zipstorer#43]
Raise this error
No data is available for encoding 437. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.

as workaround i comment the lines
private static Encoding DefaultEncoding = Encoding.UTF8/* Encoding.GetEncoding(437)*/;

**Comment by jaime-olivares** [comment]
I have added it to the static constructor
