### ISSUE TITLE
The library does not notice a file is not in Zip format

### ISSUE THREAD

**Issue by aljaz0** [jaime-olivares/zipstorer#45]
Hey,
I noticed the library does not check the file stamp to determine if the filew passed in is  a Zip file.  I passed in a .Rar archive by mistake and it started parsing away and crashing eventually. I created a simple fix that checks for the ZIP filestamp (0x50,0x4b,0x03, 0x04) before parsing to avoid that. I hope I am notr missing anything ?

**Comment by jaime-olivares** [comment]
I don't think this is a correct assessment. 
First thing done is to find the End of Centra Directory section, which obviously fails and intentionally throws an InvalidDataException.
I have tried it with a sample .rar file.
