### ISSUE TITLE
Fixing "Archive is corrupt" while unpacking added to ZIP null-bytes files.

### ISSUE THREAD

**Issue by thehydracreator** [jaime-olivares/zipstorer#49]
To fix this issue, just add in "Store":

if (_source.Length == 0)
{
    _zfe.FileSize = 0;
    _zfe.CompressedSize = 0;
    _zfe.Crc32 = 0;
    _zfe.Method = Compression.Store;
    return _zfe.Method;
}

**Comment by jaime-olivares** [comment]
Implemented as suggested
