### ISSUE TITLE
Feature suggestions

### ISSUE THREAD

**Issue by jaime-olivares** [jaime-olivares/zipstorer#5]
Hi all, I am planning to give this old library a new life. Please suggest features that you may not found in the existing Microsoft APIs. Take into account that this is a small library without dependencies (with exception of the Deflate class), so I won't be inclined to add very complex functionalities. Thanks.

**Comment by Coloris** [comment]
Hello, it would be great if this library could **assist** in creating AppX files (not to generate any XML metadata files but to provide a way to get the compressed size of each 64kb block) with Zip64 + Deflate64 support. Something like this but in .Net : https://stackoverflow.com/questions/38806524/determine-the-compressed-block-size-with-zlib-minizip

**Comment by DarkByte7** [comment]
Method for showing progress value for files being packed or extracted.

**Comment by astrohart** [comment]
Would need to have support for extracting files from ZIP files more than 4 GB in size (I am slinging a ZIP which is 14 GB in size, compressed using Windows Explorer menus, around to set up servers).

**Comment by jaime-olivares** [comment]
@astrohart You request will be covered in https://github.com/jaime-olivares/zipstorer/issues/17

**Comment by harper23** [comment]
Your ReadFileInfo checks that the central directory is at the end of file. This inhibits to add a certificate at the end. If would be good to have an option to allow to find the central directory within a range at the end of file.
