### ISSUE TITLE
Issue with DosTimeToDateTime routine when the original modify time is not set

### ISSUE THREAD

**Issue by KrayziePK** [jaime-olivares/zipstorer#8]
I found an issue with the DosTimeToDateTime routine. I have a KMZ file from which I wanted to extract the underlying KML file. However, the KML file does not have any attributes/metadata specified. This causes the class to crash when calling the DosTimeToDateTime routine with 0 as the argument. I modified the routine as following:

```
private DateTime DosTimeToDateTime(uint _dt)
{
    int year = (int)(_dt >> 25) + 1980;
    int month = (int)(_dt >> 21) & 15;
    int day = (int)(_dt >> 16) & 31;
    int hour = (int)(_dt >> 11) & 31;
    int minute = (int)(_dt >> 5) & 63;
    int second = (int)(_dt & 31) * 2;

    return new DateTime(year, month == 0 ? 1 : month, day == 0 ? 1 : day, hour, minute, second);
}

```
Maybe returning DateTime.Now would be better. Either way, in case the modify date/time stamp is missing, the original code crashes.

**Comment by jaime-olivares** [comment]
Hi, thanks for going through this. It is surprising nobody noticed that in 9 years!
Regarding the return value, I can see two choices: 
- Return null. That will need to change the return type to `DateTime?` and will break the code of hundreds of users
- Return [DateTime.MinValue](https://msdn.microsoft.com/en-us/library/system.datetime.minvalue(v=vs.110).aspx). Although not ideal, it sounds like the less-impact alternative.

Returning `DateTime.Now` doesn't sound good to me because it can be misleading, but you can add an external logic to convert `.MinValue` to `.Now`

**Comment by KrayziePK** [comment]
So I tested the DateTime.MinValue. However that value cannot be used for the File.SetCreationTime and File.SetLastWriteTime routines thus the file extraction crashes.

**Comment by jaime-olivares** [comment]
what is the effect when you use other tools? I would like to be consistent with those.

**Comment by KrayziePK** [comment]
I can only test 7zip and the in-built Zip extraction in Windows Explorer. In case there is no date/time attribute then 7zip uses the date/time stamp of the parent zip file and the Windows in-built Zip extraction does not set any date/time flags at all for the extracted file.

**Comment by jaime-olivares** [comment]
OK, the 7zip approach sounds reasonable. Regarding the built-in Windows approach, not sure what you mean with 'not set at all', the files should have any date.

**Comment by KrayziePK** [comment]
Sorry, you are right. The extracted file had 'Friday, ‎January ‎12, ‎1601, ‏‎12:40:16' set as the Created/Modified/Accessed attributes. However, these stamps are not visible in the Detail view of Windows Explorer so I thought they were not set at all.

**Comment by jaime-olivares** [comment]
I have just published the nuget package ZipStorer 3.2 (https://www.nuget.org/packages/ZipStorer/3.2.0) with support for .Net 2.0+ and .Net Standard 1.6
I have not windows right now, can you try if it works ok? That includes the modification of date.

**Comment by KrayziePK** [comment]
I am sorry but I have no experience with NuGet packages. I tried to install it for a freshly generated WinForms project, it successfully installed. However, for some reason I can't reference it and even when I add `using System.IO.Compression;` I can't seem to find the ZipStorer class.

**Comment by jaime-olivares** [comment]
ok I will run a VM and try it. After I confirm the nuget package generation is ok, I will commit it.

**Comment by jaime-olivares** [comment]
Included the suggested change in the last version
